// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfmWPkTxMXrfCLZaHuBriFOq9HKGLqD0s',
    appId: '1:777197176818:web:b14d49f94c55fe80b44d6b',
    messagingSenderId: '777197176818',
    projectId: 'flutter-appchat-g2',
    authDomain: 'flutter-appchat-g2.firebaseapp.com',
    storageBucket: 'flutter-appchat-g2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8ZD5QX6_nxZJN4SOIKLgCaOJ95bw_Aj4',
    appId: '1:777197176818:android:854278891cf3b4feb44d6b',
    messagingSenderId: '777197176818',
    projectId: 'flutter-appchat-g2',
    storageBucket: 'flutter-appchat-g2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvdtJIFFp92JqSs7S9_Gl2ZLg6uTyyMI8',
    appId: '1:777197176818:ios:618a677f97abee8ab44d6b',
    messagingSenderId: '777197176818',
    projectId: 'flutter-appchat-g2',
    storageBucket: 'flutter-appchat-g2.appspot.com',
    iosBundleId: 'com.example.flutterAppchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvdtJIFFp92JqSs7S9_Gl2ZLg6uTyyMI8',
    appId: '1:777197176818:ios:618a677f97abee8ab44d6b',
    messagingSenderId: '777197176818',
    projectId: 'flutter-appchat-g2',
    storageBucket: 'flutter-appchat-g2.appspot.com',
    iosBundleId: 'com.example.flutterAppchat',
  );
}
